version: "3.0"

services:
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - app

    app:
        build: ./app
        expose:
            - "8000"
